### PR TITLE
docs: fix README.md

### PR DESCRIPTION
**Pull request by kcoderhtml**
I noticed some things were wrong with the README, so I'm going through and fixing them; this PR isn't ready to merge yet though.

### CODE REVIEW

**Comment by JosiasAurel** [comment]
when do you think this PR will be ready for review?

would suggest also mentioning that test version of scrappy run in #scrapbook-test channel among others.

**Comment by kcoderhtml** [comment]
Oops; i forgot I had this open. I was waiting to hear what commands were still available, so I could update them in the README.

**Comment by kcoderhtml** [comment]
Just checked the commands, and it seems that the webhook isn't implemented anymore?

**Comment by JosiasAurel** [comment]
> Just checked the commands, and it seems that the webhook isn't implemented anymore?

looks like it

**Comment by kcoderhtml** [comment]
Sad; could I create a PR to add it back?

**Comment by JosiasAurel** [comment]
you can go ahead and do so but there are currently plans to make big changes to how scrappy works

**Comment by kcoderhtml** [comment]
ooh; nvm then i'll wait for that then

**Comment by kcoderhtml** [comment]
This should be ready to merge now

**Comment by JosiasAurel** [comment]
yep

**Pull request merged**
