### PR TITLE
Hyphenate Commands

### PR DESCRIPTION
**Pull request by sampoder**
I think some stuff needs to be done in the Slack App Centre / dev portal thing

### CODE REVIEW

**Comment by sampoder** [comment]
@lachlanjc would you like it to be all the stuff or really just what the user sees

**Comment by sampoder** [comment]
oh also might fix #63

**Comment by MatthewStanciu** [comment]
🤔 This isn't really what I was thinking. I was thinking more instead of a main `scrappy` command and `/scrappy updatestreaks`, it's `/scrappy-updatestreaks` etc. so that the commands appear directly in Slack's helper menu thing without you having to type `/scrappy` or `/scrappy help` to remember what they are.

Let me know if you're up for doing that. If you are, would you mind closing and reopening this PR? Also, assume the Slack command stuff is taken care of already (I'll make sure to do that before I merge).

**Comment by sampoder** [comment]
I'm not sure how to do that :/

**Comment by MatthewStanciu** [comment]
No worries, I can do it!

**Pull request closed without merging**
