### PR TITLE
Too Long Error for Webbings

### PR DESCRIPTION
**Pull request by sampoder**
Context: https://hackclub.slack.com/archives/G012QMUFP7W/p1594994261016400

### CODE REVIEW

**Comment by sampoder** [comment]
@MatthewStanciu should I also resolve these conflicts

**Comment by MatthewStanciu** [comment]
yes pleaseee, sorry abt this

**Comment by sampoder** [comment]
what am I doing

**Comment by sampoder** [comment]
this pr is such a mess

**Comment by sampoder** [comment]
I'm going to clean it all up

**Comment by MatthewStanciu** [comment]
yay lmk when ready

**Comment by sampoder** [comment]
ok @MatthewStanciu I think this is ready

**Comment by MatthewStanciu** [comment]
yay

**Comment by MatthewStanciu** [comment]
it work!!!

**Comment by MatthewStanciu** [comment]
wait no, now i can't remove anyone from my webring because i ahve 8

**Comment by sampoder** [comment]
oh noooo

**Comment by sampoder** [comment]
I'll fix

**Comment by MatthewStanciu** [comment]
oh

**Comment by MatthewStanciu** [comment]
i just fixed it

**Comment by sampoder** [comment]
ahhh I saw

**Pull request merged**
