### PR TITLE
Change emoji from spring to summer

### PR DESCRIPTION
**Pull request by eilla1**
This pr changes the default scrappy emoji reaction from :spring-of-making: to :summer-of-making: because it's summertime.

### CODE REVIEW

**Comment by l3gacyb3ta** [comment]
bump!

**Comment by BetsyZhang10** [comment]
bump x2!

**Comment by MatthewStanciu** [comment]
I agree that the emoji needs to be changed but I don’t agree that it should be the original :summer-of-making:. One thing that that emoji provides is an archive of the 2020 summer of making, and I think it should stay that way. Could we design one that’s similar but like orange or something? 👀

**Comment by BetsyZhang10** [comment]
> I agree that the emoji needs to be changed but I don’t agree that it should be the original :summer-of-making:. One thing that that emoji provides is an archive of the 2020 summer of making, and I think it should stay that way. Could we design one that’s similar but like orange or something? 👀

True. I'll think of some ideas too :)

**Comment by BetsyZhang10** [comment]
I made a really quick drawing and left it on scrapbook for ideas.

**Comment by eilla1** [comment]
I tried my hand at a similar design but orange. Let me know what you think! (the second one is currently on slack as :som-21: but i can change it if need be)
Som-21
Som-21

**Comment by sampoder** [comment]
could we make it just `:summer:`?

**Comment by sampoder** [comment]
Actually, there's some exciting stuff coming up re summer so let's give this a bit more time

**Comment by eilla1** [comment]
sounds good; looking forward to whatever is happening this summer! 👀

**Comment by MatthewStanciu** [comment]
I’m actually in favor of merging this with the new summer-21 emoji if you’re okay with it @sampoder because I think scrappy really needs to stop replying with spring-of-making when it’s almost July lol

**Comment by sampoder** [comment]
Ya, that's fair. Online stuff seems to blocked so let's merge this

**Review by sampoder — APPROVED** [review]

**Pull request merged**
