### PR TITLE
Implemented reaction thing

### PR DESCRIPTION
**Pull request by cjdenio**
This PR implements the reaction in other channels thing. *PLEASE NOTE* that while this won't break existing Scrappy functionality, it may not fully work.

## ⚠️ WARNING

This PR requires Scrappy to have the `channels:read` scope, if it doesn't already.

### CODE REVIEW

**Comment by sampoder** [comment]
Yay!!!

**Comment by MatthewStanciu** [comment]
Thanks so much!! Merging and testing now

**Comment by cjdenio** [comment]
Yay! Let me know if it doesn't work.

**Comment by sampoder** [comment]
you are entering dangerous waters.... the world of scrappy testing

**Comment by cjdenio** [comment]
Fortunately, I brought my life vest ⛵

**Comment by sampoder** [comment]
how long do you all think it will take to build?

**Comment by cjdenio** [comment]
OK; tried it out and looks like it got stuck on the beachball reaction. @MatthewStanciu could you look at the logs real quick?
image

**Comment by sampoder** [comment]
looks like the waters are rough 🌊

**Comment by MatthewStanciu** [comment]
🤔 🤔 🤔 I just tried it in my club channel (#westlafayette) and nothing happened, not even a beachball. The logs say nothing 🤔 🤔 🤔

**Comment by MatthewStanciu** [comment]
something's wrong, captain

**Comment by MatthewStanciu** [comment]
Ok so one problem is that if Scrappy isn't in the channel you're reacting in, it doesn't do anything, which is bad because I wanted Scrapbook to play a role in the new clubs program. Hopefully there's a way around it.

Anyway I added Scrappy to my club channel and now I did get a beachball. The logs say `formatText is not defined`, which sounds like a very easily solvable problem. Brb 🎉

**Comment by cjdenio** [comment]
Yeah, there's no way to detect a reaction in a channel the bot's not in. Maybe we could do something like what The Fuzz does?

**Comment by cjdenio** [comment]
Also @MatthewStanciu I fixed the issue

**Comment by MatthewStanciu** [comment]
https://hackclub.slack.com/archives/C4RN4PLLW/p1598541632001500 it work ! !!!!!!

**Comment by MatthewStanciu** [comment]
Ok so one more problem is that when you delete your post, it doesn't delete the post from scrapbook

**Comment by cjdenio** [comment]
Woo-hoo!

**Comment by sampoder** [comment]
hey @cjdenio and @MatthewStanciu is this good to go for tomorrow's announcement?

**Comment by cjdenio** [comment]
@MatthewStanciu cool PR :arrow_right: #100

**Pull request merged**
