### PR TITLE
[WIP] feat: make scrappy cuss

### PR DESCRIPTION
**Pull request by l3gacyb3ta**
Y'all are welcome

### CODE REVIEW

**Comment by cole-wilson** [comment]
wow

**Comment by l3gacyb3ta** [comment]
@zfogg @zachlatta yall better merge this

**Comment by zfogg** [comment]
sus

**Comment by zfogg** [comment]
probably not the best vibe for the community because newcomers may tag scrappy their very first day. although it is funny. i am on the fence.

**Comment by l3gacyb3ta** [comment]
saaaaame I want it so bad tho, and that'd be a fun introduction to a bot tbh

**Comment by MatthewStanciu** [comment]
I am against merging. Because I am annoying

**Comment by l3gacyb3ta** [comment]
Thanks matthew

**Comment by l3gacyb3ta** [comment]
OK, new idea, scrappy will cuss back at you

**Comment by gleich** [comment]
:shipit:

**Comment by l3gacyb3ta** [comment]
thanks ian!

**Review by sampoder — CHANGES_REQUESTED** [review]
nah

**Comment by eilla1** [comment]
i must disagree with this PR; i think swearing to a certain degree is ok, but i think these responses could arguably be considered a violation of the CoC because it kind of falls under the "insulting, demeaning, hateful, or threatening remarks" category.

**Comment by quackduck** [comment]
Doesn’t fit with Scrappy’s personality, I’m not for this. Would be much nicer if the insults were low level like “dum-dum” or “dummy” or “idiot!!!” (Idiot may be too much)

**Comment by quackduck** [comment]
I would find and replace those swears with the low level ones, that would make it actually funny.

**Comment by aidenybai** [comment]
pg-13 scrappy fork wen

**Comment by l3gacyb3ta** [comment]
okie dokie artachokie how bout this? That way it's opt in!

**Comment by maxwofford** [comment]
@quackduck @aidenybai @eilla1 if you have ideas on 'scrappy' flavored insults, i'd love to hear them! working on https://github.com/l3gacyb3ta/scrappy/pull/1, but kinda stuck on more alternatives

**Pull request closed without merging**
