### PR TITLE
Add Steal Command

### PR DESCRIPTION
**Pull request by sampoder**
This command allows you to steal someones css, its late so lemme know if the wording should be changed idk it its right ya

### CODE REVIEW

**Comment by sampoder** [comment]
also pls let me know if I've done this wrong, I haven't even tested this lol

**Comment by sampoder** [comment]
my code wasn't pretty :( I will fix

**Comment by sampoder** [comment]
🎉 amazing!

**Comment by sampoder** [comment]
@Matt-Gleich keeping me to high standards

**Comment by lachlanjc** [comment]
Let’s do `steal-css`? Unclear what you’re stealing otherwise I think

**Comment by sampoder** [comment]
ya that makes more sense, thanks @lachlanjc

**Comment by MatthewStanciu** [comment]
Yay is this ready to merge? @sampoder

**Comment by sampoder** [comment]
yep but I think you need to do some stuff on scrappyes end

**Comment by MatthewStanciu** [comment]
Ok blind merge here we go

**Comment by sampoder** [comment]
hmmmmmm

**Comment by sampoder** [comment]
did I do smth wrong?

**Comment by sampoder** [comment]
it worked!!!

**Comment by sampoder** [comment]
@maxwofford I have stolen you css lol

**Pull request merged**
