### PR TITLE
Add all of the emojis!!

### LINKED ISSUE #16: Transform non-custom emoji
This should be super simple, happy to assist. Basically, run node-emoji to switch colon-emoji-colon into Unicode characters. We can ignore custom emoji for now, but would be nice to fix up the regular ones https://www.npmjs.com/package/node-emoji

### PR DESCRIPTION
**Pull request by sampoder**
🤯 

fixes #16

### CODE REVIEW

**Comment by sampoder** [comment]
fixes #16

**Comment by lachlanjc** [comment]
Looks good to me!

**Comment by sampoder** [comment]
it seems that this didn't work

https://hackclub.slack.com/archives/C01504DCLVD/p1592754113217100

**Comment by sampoder** [comment]
https://repl.it/@sampoder/PunyDarkvioletCharmap#index.js

code seems to be fine here

**Comment by lachlanjc** [comment]
image

Looks like it’s working!

**Comment by sampoder** [comment]
yep it is now, yay!

**Pull request merged**
