### PR TITLE
Remove random emoji

### PR DESCRIPTION
**Pull request by maxwofford**
With the addition of the tagging feature I think we'll want to turn this off https://scrapbook.hackclub.com/r/party-dinosaur

### CODE REVIEW

**Comment by sampoder** [comment]
Hmmm ya that kind of makes sense but the channel is very dull where everyone has the Summer react. imo, it seemed the most authentic when we just responded with a random emoji, not sure why the sun one is needed.

**Comment by maxwofford** [comment]
@sampoder if we want the scrapbook to run after the summer, we have an automatically created archive page for the whole summer https://scrapbook.hackclub.com/r/summer-of-making

**Comment by sampoder** [comment]
ahhh I didn't think of that makes sense

**Comment by maxwofford** [comment]
Would love your thoughts on how to get people to use their own reactions though– I totally agree that everyone just clicking the SOM reaction looks super boring

**Comment by sampoder** [comment]
maybe like different emojis based on keywords?

**Comment by MatthewStanciu** [comment]
Yay!

**Comment by lachlanjc** [comment]
Maybe we don’t want to venture into this territory, but could be fun to do some automatic tagging/reacting based on keywords. Searching for the names of certain kinds of emojis in the post (`package` or `keyboard` or `art` or something), or a list of keywords we assign to certain emojis (like `art`)?

**Comment by MatthewStanciu** [comment]
I agree, but only in certain cases. E.g. I would love to see keyword tagging with things like "Figma", where it's directly tied to some event and it's near-impossible to fake it.

**Comment by sampoder** [comment]
+1 https://github.com/hackclub/scrappy/pull/58#issuecomment-656736494

**Pull request merged**
