### PR TITLE
Add some more responses to mentionKeyword and mention!

### PR DESCRIPTION
**Pull request by kayleyseow**
:) 
https://cloud-r8zkxq6k0.vercel.app/image.png

### CODE REVIEW

**Review by lachlanjc — APPROVED** [review]

**Review by saharshy29 — APPROVED** [review]
Haha. I like these additions

**Comment by kayleyseow** [comment]
> Haha. I like these additions

Thank you! Can't wait to see them 😂

**Review by Muirrum — APPROVED** [review]
LGTM

**Comment by MatthewStanciu** [comment]
These are amazing, tysm

**Comment by MatthewStanciu** [comment]
(fixed merge conflict from previous pr merge ^)

**Pull request merged**
