### PR TITLE
Now You Can't Add Yourself To Your Own Webring

### LINKED ISSUE #77: Was able to add myself to my webring
20200715_22h33m27s_grim

### PR DESCRIPTION
**Pull request by sampoder**
why did I capitalise that need to add an error message

also might fix #77

### CODE REVIEW

**Comment by sampoder** [comment]
yippeee its ready

**Comment by sampoder** [comment]
@MatthewStanciu would you like me to resolve the conflicts?

**Comment by MatthewStanciu** [comment]
o nooo i'm sorry i forgot about this pr. yeah i would love it if you could resolve the conflicts 🙌 and then i'll review and merge

**Comment by sampoder** [comment]
I think the conflicts are because someone ran prettier

**Comment by sampoder** [comment]
yo what have I done

**Comment by sampoder** [comment]
nooooooo

**Comment by MatthewStanciu** [comment]
oh yeah emojis in the transcript are weird. i think the one where you do :watchingyou: needs to be in quotes

**Comment by MatthewStanciu** [comment]
YAY

**Comment by sampoder** [comment]
ALLL CHECKS HAVE PASSSEEEEDDDDD LETS GOOOOO

```
    yourself:
      - |
        Hey! :watchingyou:  Add other people to your webring, not yourself!!!!
```

**Comment by sampoder** [comment]
@MatthewStanciu is it cool if you review and merge this one then I work on resolving conflicts in #81 as this will introduce more conflicts

**Comment by MatthewStanciu** [comment]
Yep, will merge. Just be aware that it may break some parts of scrapbook and we'll have to fix, so there's a chance it'll take a little bit of time

**Comment by sampoder** [comment]
that's fine dw, my prs always break stuff

**Comment by sampoder** [comment]
Screenshot 2020-07-23 at 11 58 05 PM


adding worked

also removing
Screenshot 2020-07-23 at 11 58 29 PM

**Comment by sampoder** [comment]
Screenshot 2020-07-23 at 11 58 59 PM


but I still worked :(

**Comment by sampoder** [comment]
wait maybe It needs to build

**Comment by MatthewStanciu** [comment]
no it doesn't work, just pushed a (hopefully) fix

**Comment by sampoder** [comment]
very sad day

**Comment by sampoder** [comment]
@MatthewStanciu any tips for how I can test my code next time? because I can't code first try

**Comment by MatthewStanciu** [comment]
ok i fixed it

**Comment by sampoder** [comment]
:yay:!!! thank u

**Comment by MatthewStanciu** [comment]
there's no good way to test your code :( we've talked about this among the team and we're going to try to build a really good test suite for slack apps. but basically the only way to test is to test in production. don't worry about testing prs, just do your best and i can fix any errors

**Comment by sampoder** [comment]
ahhh ok cool will do

**Pull request merged**
