### PR TITLE
Fix editing?

### PR DESCRIPTION
**Pull request by reesericci**
This PRS will hopefull fix editing

### CODE REVIEW

**Comment by sampoder** [comment]
wow fast

**Comment by reesericci** [comment]
#42

**Comment by reesericci** [comment]
@sampoder can you pls test this PRS, i can't but I think this should fix it

**Comment by sampoder** [comment]
I'm not that great at Javascript, I think Matthew knows best lol

**Comment by reesericci** [comment]
@MatthewStanciu test?

**Comment by sampoder** [comment]
It's early in America, hang tight

**Comment by reesericci** [comment]
i'm up at 6 hahaha

**Comment by sampoder** [comment]
Dedication

**Comment by MatthewStanciu** [comment]
Sorry was taking a shower lol. Reviewing now

**Comment by MatthewStanciu** [comment]
This will fix it but it will also reintroduce #14, which is what adding that line fixed. I see two paths forward:

1. Finding a way to fix both this issue and #14 
2. Merging this PR as-is and updating updated.js to remove the beachball emoji if it tries and fails to update a scrapbook post (which is what happens in threaded messages because there is no post to update)

Thoughts?

**Comment by reesericci** [comment]
We should just remove the beachball alltogether until we can reach point no. 1 and merge this PRS. Re-open issue #14 once merged.

**Comment by reesericci** [comment]
any updates?

**Comment by MatthewStanciu** [comment]
Going to go with path 2! Merging now

**Comment by MatthewStanciu** [comment]
Yay! It works! Went ahead and just removed the beachballs anyway—they appear and disappear too quickly for anyone to notice them.

**Pull request merged**
